### ISSUE TITLE
Update copy to be more inclusive

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/sheltertech.org#142]
There are several places where could update the copy to use more inclusive language.

## Home page
- In the site `<title>`, the word "underserved" should be replaced with "under-resourced"
- In the "Get Involved" section, replace the word "empower" with "connect"
- In the third quote in the block quote component, the word "vulnerable" should be replaced with "[at-risk]". Since it's a quote, this replacement should include the square brackets

## Volunteer page
- In the hero banner, "vulnerable" should be replaced with "at-risk"
- In the "Let's work together" section, "underserved" should be replaced with "under-resourced"

## Donate page
- The word "underserved" should be replaced with "under-resourced"

**Comment by davidagustin** [comment]
Unable to do task in Homepage: "In the site <title>, the word "underserved" should be replaced with "under-resourced" ; Could not find word underserved

**Comment by richardxia** [comment]
> Unable to do task in Homepage: "In the site <title>, the word "underserved" should be replaced with "under-resourced" ; Could not find word underserved

It's right over here, in layout.js: https://github.com/ShelterTechSF/sheltertech.org/blob/5a5ed440f113cbc9aff788b96982c801eae5f45d/src/components/layout.js#L39
