### ISSUE TITLE
Automate, or simplify, event updates

### ISSUE THREAD

**Issue by derekfidler** [ShelterTechSF/sheltertech.org#18]
Currently the events and volunteer pages need to be updated manually for every new event that is added and then again after the event's date has passed. This requires a little, but frequent, amount of developer time each week. It would be better to simplify this process so a non-developer can update this page and it automatically sorts events based on upcoming or past.

**Comment by richardxia** [comment]
Going to close this out, as this will be addressed by the Prismic CMS project.
