### ISSUE TITLE
"Replace references to "AskDarcel" app in sheltertech.org with "SF Service Guide"

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/sheltertech.org#20]
@fredciaramaglia commented on [Tue May 21 2019](https://github.com/ShelterTechSF/askdarcel-web/issues/761)

---

@fredciaramaglia commented on [Tue May 21 2019](https://github.com/ShelterTechSF/askdarcel-web/issues/761#issuecomment-494663144)

Since the SF Service Guide app links to sheltertech.org in several places, before the release of SF Service Guide we need to replace the many "AskDarcel" references with "SF Service Guide", in the following places:
1. Programs page - AskDarcel name and graphic
2. Impact page - AskDarcel name and graphic
3. Get Involved page
4. Team page
5. Several of the Blog articles

This issue is related to Issue 760: "Replace references to "AskDarcel" app in SF Service Guide with "SF Service Guide" and probably should be done at the same time.

**Comment by richardxia** [comment]
@derekfidler did this in 9f524a0afe71df853f64a0de4c232e70d84a1773.
