### ISSUE TITLE
Figure out if we can add comments to graphql queries

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/sheltertech.org#230]

**Comment by jessica-px** [comment]
I have no idea what we were doing wrong before, but the `#` character seems to correctly create comments now. I was able to get this query to work with comments in all of these positions:

```javascript
export const query = graphql`
  # above query
  query MyQuery {
    # inside query
    prismicFooter {
      # inside a thing inside the query
      ...FooterFragment
    }
  }
`;
```

@richardxia Can you try putting `#` comments in a query and see if you still run into problems??

**Comment by richardxia** [comment]
Yeah, that looks like it works for me. I guess I'd chalk it up to the Gatsby Prismic GraphQL stuff being a little bit flaky when you first get things set up, so it probably just coincidentally failed for other reasons.

Still good to confirm that the comment character is `#` for these GraphQL queries.
