### ISSUE TITLE
Upgrade gatsby-source-prismic

### ISSUE THREAD

**Issue by jessica-px** [ShelterTechSF/sheltertech.org#256]
My current progress trying to upgrade gatsby following the steps in these guides:
- https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/
- https://github.com/angeloashmore/gatsby-source-prismic/blob/alpha/packages/gatsby-source-prismic/docs/migrating-from-v3-to-v4.md

I'm currently getting this error when I try to run `npm run start`:

```
ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

undefined

If you're trying to use a package make sure that 'undefined' is installed. If you're trying to use a
 local file make sure that the path is correct.

failed Building development bundle - 25.595s
ERROR in commons
Module not found: TypeError: Cannot read property 'indexOf' of undefined
```

It's hard for me to tell exactly what's causing the error. Because the old version of `gatsby-source-prismic` won't work with the new version of `gatsby`, I had to (try to) upgrade them at the same time. But this makes debugging harder. My next step was going to be the branch off of `main` and see if I could get gatsby upgraded on its own, without prismic.

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
