### ISSUE TITLE
Create HOC for Prismic page previews

### ISSUE THREAD

**Issue by jessica-px** [ShelterTechSF/sheltertech.org#283]
Currently we have to wrap every previewable page like this:

```
export default withPrismicPreview(IndexPage, [
  {
    repositoryName: "sheltertech",
    linkResolver,
  },
]);
```
This isn't the worst thing in the world, but it's annoying to import multiple things and provide the same parameters over and over. So let's just make our own HOC that wraps this export code around our pages.

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
