### ISSUE TITLE
Little Green Light iFrame under "Donate" on sheltertech.org

### ISSUE THREAD

**Issue by dseo1212** [ShelterTechSF/sheltertech.org#345]
**Amount*> Igld-radio-label (i.e.$36) > Tab > other input text**

The selected amount (i.e. $36) should remain selected until a user types in a value into the "other" input text field. See [Figma](https://www.figma.com/file/nlnQ4iyBehs7k5e44ldjLR/Conformance-Testing?node-id=32%3A125&t=duPDmQh5hIosKTYK-4) for details

**Example Behavior:**
![image](https://user-images.githubusercontent.com/122650443/213066105-36aae3b7-a0e9-4470-8231-21e2a6409e38.png)

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
