### ISSUE TITLE
Improve Repetitive Content Accessibility

### ISSUE THREAD

**Issue by schroerbrian** [ShelterTechSF/sheltertech.org#354]
See relevant row in [accessibility spreadsheet](https://docs.google.com/spreadsheets/d/1wk4l1ZjWCvxJF0Xjuco8b-lWVws-Vo0aIIRkCYRjbIc/edit#gid=0) for details

**Comment by MohitBansal321** [comment]
i can't access

**Comment by schroerbrian** [comment]
> accessibility spreadsheet

Hi @MohitBansal321  -- we have made the link public. Please let me know if you can't access it now.

**Comment by MohitBansal321** [comment]
2.4.7-focus-visible (buttons, links, form controls)
I want to solve this issue
but I need help regarding this

**Comment by schroerbrian** [comment]
Hi @MohitBansal321 what sort of help would you like? Here is the [ticket](https://github.com/ShelterTechSF/sheltertech.org/issues/350) for that issue. It involves displaying an outline around the focused button, link, or input field. You can use the native browser default outline as a start. Please let me know if you have further questions.

**Comment by MohitBansal321** [comment]
I can't  able to understand which issue is resolved or not 
@schroerbrian

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
