### ISSUE TITLE
Improve Sensory Characteristics & Contrast Accessibility

### ISSUE THREAD

**Issue by schroerbrian** [ShelterTechSF/sheltertech.org#358]
See relevant row in [accessibility spreadsheet](https://docs.google.com/spreadsheets/d/1wk4l1ZjWCvxJF0Xjuco8b-lWVws-Vo0aIIRkCYRjbIc/edit#gid=0) for details

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
