### ISSUE TITLE
Fix video overlay/intercom in the mobile view in landscape mode

### ISSUE THREAD

**Issue by candywang** [ShelterTechSF/sheltertech.org#363]
The Home page has a play button that when clicked, displays a YouTube video as an overlay. In the mobile view in landscape mode, the intercom interferes or blocks the ability to click on the full screen button for the video.

![Screenshot 2023-06-14 at 1 07 50 AM](https://github.com/ShelterTechSF/sheltertech.org/assets/39474473/7c79bdb8-1d0e-46cc-9e16-a3b3e921ae21)

**Comment by richardxia** [comment]
Closing, as we are in the process of porting the site to a no-code platform, Wix, so that the non-engineering teams at ShelterTech can maintain the corporate site on their own.
