### ISSUE TITLE
Logo and donate visuals are broken on mobile

### ISSUE THREAD

**Issue by derekfidler** [ShelterTechSF/sheltertech.org#7]

**Comment by toChaim** [comment]
I looked at this. The text of the top component on the home page is getting cut off at the top and it has no background image. Are these the problems you have?
If so they are set on the style sheet for the component. sheltertech.org/src/routes/Home/components/HomeView.scss
line 15 sets the height to half the screen size. I think that is meant to be minimum height.
min-height: 50vh;
Or you could scale down the text so it fits in only half the screen.
Line 23 removes the background image. Just remove it to bring the image back.

I will put in a pull request with these changes. If I have the problem wrong or you want a different solution reply here or put it as a comment on the pull request. 
Thanks
Chaim
